/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class WifiUtils */

#ifndef _Included_WifiUtils
#define _Included_WifiUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     WifiUtils
 * Method:    initialize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_WifiUtils_initialize
  (JNIEnv *, jclass);

/*
 * Class:     WifiUtils
 * Method:    updateStats
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_WifiUtils_updateStats
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
